### ISSUE TITLE
Preprocessing failure

### ISSUE THREAD

**Issue by neon5d** [HzFu/EyeQ#2]
Two training images and three testing images are failed during the preprocessing.
But they are still included in the test set.
Can you clarify these images?

For training, 
15337_left.jpeg
40764_right.jpeg
For testing,
13227_left.jpeg
26250_left.jpeg
5371_left.jpeg

**Comment by HzFu** [comment]
Yes, several images could not be processed by the preprocessing code. You may need to crop them manually.
Thank you for mention that, I will claim them in readme.
