### ISSUE TITLE
Included results

### ISSUE THREAD

**Issue by agaldran** [HzFu/EyeQ#5]
Dear authors,

Thank you very much for releasing your work. I have one question regarding your published results: I have used the `MCF_Net/result/DenseNet121_v3_v1.csv` file to compute accuracy in the test set, and unless I am making some silly mistake, I obtain an accuracy of `88.00%`. However, the results in your MICCAI paper, last row of table 2, show an accuracy of `91.25%`. Is there any way you could double-check this inconsistency, and/or upload the csv corresponding to those results?

Thank you so much,

Adrian

**Comment by HzFu** [comment]
We have updated the accuracy score.
